# Generated by Django 4.2.30 on 2026-04-28 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(choices=[('drawing', 'Drawing / Blueprint'), ('specification', 'Technical Specification'), ('boq', 'Bill of Quantities'), ('contract', 'Contract / Agreement'), ('tender', 'Tender Document'), ('rfi', 'Request for Information'), ('submittal', 'Submittal'), ('safety', 'Safety / HSE Report'), ('inspection', 'Inspection Report'), ('progress', 'Progress Report'), ('permit', 'Permit / Approval'), ('invoice', 'Invoice / Payment'), ('site_photo', 'Site Photo'), ('other', 'Other')], default='other', max_length=32)),
                ('discipline', models.CharField(blank=True, help_text='Civil, Structural, Architectural, MEP, etc.', max_length=64)),
                ('revision', models.CharField(blank=True, max_length=32)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
