# Generated by Django 4.2.30 on 2026-04-28 06:45

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.BigIntegerField(db_index=True)),
                ('text', models.TextField()),
                ('page', models.IntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('language', models.CharField(default='unknown', max_length=8)),
                ('document_title', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(blank=True, max_length=32)),
                ('discipline', models.CharField(blank=True, max_length=64)),
                ('revision', models.CharField(blank=True, max_length=32)),
                ('project_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='rag_chunk_embedding_hnsw', opclasses=['vector_cosine_ops']), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='rag_chunk_tags_gin'), models.Index(fields=['document_type'], name='rag_chunk_documen_4308a1_idx'), models.Index(fields=['language'], name='rag_chunk_languag_06366c_idx')],
            },
        ),
    ]
